import './globals.css'
import QueryWrapper from '../components/QueryWrapper'
import Header from '../components/Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='flex flex-col min-h-screen items-center py-8  bg-gradient-to-b from-slate-600 to-slate-800 text-gray-200 max-w-7xl mx-auto overflow-hidden mx-4 '>
        <QueryWrapper>
          <Header />
          {children}
        </QueryWrapper>
      </body>
    </html>
  )
}
